# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Disable POST password expiration"
  lineinfile:
    create=yes
    dest="/etc/default/useradd"
    regexp="^INACTIVE"
    line="INACTIVE=-1"
  tags:
    @ANSIBLE_TAGS@

