# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Build and Test AIDE Database"
  shell: /usr/sbin/aide --init
  tags:
    @ANSIBLE_TAGS@

- name: Stage AIDE Database"
  copy:
    src: /var/lib/aide/aide.db.new.gz
    dest: /var/lib/aide/aide.db.gz
    backup: yes
  tags:
    @ANSIBLE_TAGS@
