# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "@RULE_TITLE@"
  selinux:
    state: (ansible-populate var_selinux_state)
  tags:
    @ANSIBLE_TAGS@
