# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Set SSH Client Alive Count"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^ClientAliveCountMax"
    line="ClientAliveCountMax 0"
  tags:
    @ANSIBLE_TAGS@
