# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Disable Kerberos Authentication"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^KerberosAuthentication"
    line="KerberosAuthentication no"
  tags:
    @ANSIBLE_TAGS@
