# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Disable SSH Support for Rhosts RSA Authentication"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^RhostsRSAAuthentication"
    line="RhostsRSAAuthentication no"
  tags:
    @ANSIBLE_TAGS@
