# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Disable SSH Root Login"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
  tags:
    @ANSIBLE_TAGS@
