# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Set Account Expiration Following Inactivity
  lineinfile:
    create: yes
    dest: /etc/default/useradd
    regexp: ^INACTIVE
    line: INACTIVE=(ansible-populate var_account_disable_post_pw_expiration)
  tags:
    @ANSIBLE_TAGS@
